### ISSUE TITLE
Segmentation Fault?

### ISSUE THREAD

**Issue by jgoliveira** [nm-morais/cp_pattern_data_collection#1]
I think I may be doing something wrong, but that's what is happening to me:

![image](https://user-images.githubusercontent.com/7190315/49332311-fe9cdc00-f5a2-11e8-8e66-82c9ca40ad64.png)

Could you help me with that?

**Comment by nm-morais** [comment]
Consegues dar pull e ver se resolveu?

**Comment by nm-morais** [comment]
E consegues correr com o valgrind ? para saber a origem da segfault

**Comment by jgoliveira** [comment]
Fiz pull, e agora acontece o seguinte:
![image](https://user-images.githubusercontent.com/7190315/49332527-686ab500-f5a6-11e8-8d82-1433b51fe39d.png)

Depois de vários "aborted" lá pelo meio, o fim da execução está assim:
![image](https://user-images.githubusercontent.com/7190315/49332536-90f2af00-f5a6-11e8-95e9-d805ff9f30bb.png)

**Comment by nm-morais** [comment]
É normal que o parser tenha problemas a interpretar os resultados se o programa está a rebentar, porque o log vai estar corrompido. Consegues correr o programa com o valgrind para perceber se é um problema dos testes?

**Comment by nm-morais** [comment]
Na pasta "src" corre o seguinte: $ valgrind ./main 8 4 10

**Comment by jgoliveira** [comment]
> Na pasta "src" corre o seguinte: $ valgrind ./main 8 4 10

Resultado dessa execução:
[valgrind_log.txt](https://github.com/nm-morais/cp_pattern_data_collection/files/2636331/valgrind_log.txt)

**Comment by nm-morais** [comment]
O output do valgrind diz que o problema está no código do patterns.c. Se esse for o caso não te consigo ajudar...
Outra coisa, o crash parece ter vindo de um printf da linha 50 do teu patterns.c. Para o log de execução ser corretamente interpretado pelo parser não podes ter mais prints para além daqueles que eu incluo no bundle do tester

**Comment by nm-morais** [comment]
Presumo que descobriste o erro. Boa sorte, abraço.

**Comment by jgoliveira** [comment]
Sim, descobri o erro, e lá consegui correr e gerar outputs.
Obrigado pela ajuda, e obrigado por disponibilizarem a ferramenta

**Comment by nm-morais** [comment]
Na boa! Se te foi útil, agradecia que referisses isso no relatório :D ! Abraço
